import { Lexend } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar/Navbar";
import { Footer } from "@/components/footer/Footer";
import { MiddleFooter } from "@/components/footer/MiddleFooter";

const LexendFont = Lexend({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={LexendFont.className}>
        <Navbar />
        {children}

        <MiddleFooter />
        <Footer />
      </body>
    </html>
  );
}
